### ISSUE TITLE
Formatted texts are not showing up on .epub file

### ISSUE THREAD

**Issue by kayamaf** [rauschma/deep-js#20]
The formatted texts on .epub file are not visible.

**.html (expected)**

<img width="817" alt="Screen Shot 2020-05-10 at 4 07 38 PM" src="https://user-images.githubusercontent.com/20405049/81512833-7f075680-92d8-11ea-8a4e-9221319f9b2f.png">

**on .epub**

<img width="1076" alt="Screen Shot 2020-05-10 at 4 04 46 PM" src="https://user-images.githubusercontent.com/20405049/81512789-07392c00-92d8-11ea-84db-8b2f23efbe48.png">

**Comment by rauschma** [comment]
Thanks for reporting this! Fixed now.

The problem was that an upgrade of Apple Books broke EPUB files with horizontal scrolling (for code).

**Comment by kayamaf** [comment]
Thank you for quickly shipping the fix! 🙏
