### ISSUE TITLE
Webpage: Wrong link to free to read version

### ISSUE THREAD

**Issue by fkopp81** [rauschma/deep-js#22]
At "Free to read online (except for three bonus chapters): HTML version" the link address is https://exploringjs.com/toc.html, which leads to a "Not found" page. I found the book when I changed the link to: https://exploringjs.com/deep-js/toc.html

**Comment by rauschma** [comment]
That happens if you omit the final slash (I’d consider it a bug of my hosting service and am trying to fix this). If the final slash is missing, other things on the homepage (e.g. images) should also be broken.
